title: "道德经 · 松Song心注本"
description: "松Song 与 青隐子共修记"

# 站点地址
url: "https://songsong816.github.io"  
baseurl: "/daodejing"  

# 主题与 Markdown 解析
theme: minima
header_pages: []
markdown: kramdown

timezone: "Australia/Melbourne"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
