title: "道德经 · 松Song心注本"
description: "松Song 与 青隐子共修记"
theme: minima
markdown: kramdown

baseurl: ""                      
url: "https://songsong816.github.io"
timezone: "Australia/Melbourne"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
title: 道德经 · 松Song心注本
theme: minima
markdown: kramdown

